# Generated by Django 6.1.1 on 2026-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='audience',
            field=models.CharField(choices=[('all', 'All Users'), ('active', 'Active Users')], default='all', max_length=20),
        ),
    ]
